# Here you will find the hands on practice done during classs

In [2]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2026-02-28 23:20:17.920319


In [3]:
import numpy as np

# Check the version
print(np.__version__)

2.3.5


## Data types and attributes

In [4]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))
print(a1.dtype)
print(a1.shape)
print(a1.ndim)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [75]:
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.1, 3.3],
               [4, 5, 6.5]])
print(a2)
print(type(a2))
print(a2.dtype)
print(a2.shape)
print(a2.ndim)
print(a2.size)

[[1.  2.1 3.3]
 [4.  5.  6.5]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [76]:
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
print(a3)
print(type(a3))
print(a3.dtype)
print(a3.shape)
print(a3.ndim)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
int64
(2, 3, 3)
3
18


pandas data frames from numpy arrays, 
this is the example that how numpy is the backbone of other libraries

In [77]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)),
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  6  7  7
1  8  1  5
2  9  8  9
3  4  3  0
4  3  5  0

In [78]:
a2

array([[1. , 2.1, 3.3],
       [4. , 5. , 6.5]])

### creating arrays

In [79]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [80]:
simple_array = np.array((1, 2, 3))
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [81]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [83]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [84]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
zeros.dtype

dtype('float64')

In [86]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array_1 = np.arange(0, 10, 2)
print(range_array)
print(range_array_1)
reslt = range_array @ range_array_1
print(reslt)

[0 2 4 6 8]
[0 2 4 6 8]
120


In [87]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]], dtype=int32)

In [88]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672]])

In [89]:
np.random.random((5, 3))

array([[0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559]])

In [90]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358]])

In [91]:
np.random.rand(5, 3)

array([[0.03918779, 0.28280696, 0.12019656],
       [0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 ]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [92]:
# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

In [93]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [94]:
# Set random seed to same number as above
np.random.seed(0)

# The same random numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [95]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

### What unique values are in the array a3?

Now you've seen a few different ways to create arrays, as an exercise, try find out what NumPy function you could use to find the unique values are within the `a3` array.

You might want to search some like, "how to find the unqiue values in a numpy array".

## 3. Viewing arrays and matrices (indexing)

Remember, because arrays and matrices are both `ndarray`'s, they can be viewed in similar ways.

Let's check out our 3 arrays again.

In [96]:
a1

array([1, 2, 3])

In [97]:
a2

array([[1. , 2.1, 3.3],
       [4. , 5. , 6.5]])

In [98]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Array shapes are always listed in the format `(row, column, n, n, n...)` where `n` is optional extra dimensions.

In [99]:
a1[0]

np.int64(1)

In [100]:
a2[0]

array([1. , 2.1, 3.3])

In [101]:
a2[0]


array([1. , 2.1, 3.3])

In [102]:
# Get 2nd row (index 1) of a2
a2[1]

array([4. , 5. , 6.5])

In [103]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [104]:
a3[0, :1]

array([[1, 2, 3]])

This takes a bit of practice, especially when the dimensions get higher. Usually, it takes me a little trial and error of trying to get certain values, viewing the output in the notebook and trying again.

NumPy arrays get printed from outside to inside. This means the number at the end of the shape comes first, and the number at the start of the shape comes last.

In [105]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]], dtype=int32)

In [106]:
a4.shape

(2, 3, 4, 5)

In [107]:
# Get only the first 4 numbers of each single vector
a4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]], dtype=int32)

`a4`'s shape is (2, 3, 4, 5), this means it gets displayed like so:
* Inner most array = size 5
* Next array = size 4
* Next array = size 3
* Outer most array = size 2

## 4. Manipulating and comparing arrays
* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than Python's `.sum()` for NumPy arrays
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T`
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

In [108]:
a = np.array([1, 2])

In [109]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
#addding the abpve two arrays
a + ones

array([[2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.]])

In [111]:
a1

array([1, 2, 3])

In [112]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [113]:
# Add two arrays
a1 + ones

array([2., 3., 4.])

In [114]:
#multiplying the above two arrays
a1 * a2

array([[ 1. ,  4.2,  9.9],
       [ 4. , 10. , 19.5]])

In [115]:
# Subtract two arrays
a1 - ones

array([0., 1., 2.])

In [116]:
# Multiply two arrays
a1 * ones

array([1., 2., 3.])

In [117]:
a1.shape, a2.shape

((3,), (2, 3))

In [118]:
# This will error as the arrays have a different number of dimensions (2, 3) vs. (2, 3, 3)
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

### Broadcasting

- What is broadcasting?
    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
    
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

In [119]:
#create an array with 1 row and 10 columns
a6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
#create an array with 10 rows an 1 column
a7 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
a7

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [121]:
a6.shape, a7.shape

((10,), (10, 1))

In [122]:
#adding the above two arrays
a6 + a7

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [123]:
a1

array([1, 2, 3])

In [124]:
a2

array([[1. , 2.1, 3.3],
       [4. , 5. , 6.5]])

In [125]:
# Divide two arrays
a1 / ones

array([1., 2., 3.])

In [126]:
# Divide using floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [127]:
# Take an array to a power
a1 ** 2

array([1, 4, 9])

In [128]:
# You can also use np.square()
np.square(a1)

array([1, 4, 9])

In [129]:
# Modulus divide (what's the remainder)
a1 % 2

array([1, 0, 1])

In [130]:
# Find the log of an array
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [131]:
# Find the exponential of an array
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])