# Here you will find the hands on practice done during classs

In [1]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2026-02-06 15:00:37.607888


In [2]:
import numpy as np

# Check the version
print(np.__version__)

2.4.1


## Data types and attributes

In [12]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))
print(a1.dtype)
print(a1.shape)
print(a1.ndim)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [13]:
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.1, 3.3],
               [4, 5, 6.5]])
print(a2)
print(type(a2))
print(a2.dtype)
print(a2.shape)
print(a2.ndim)
print(a2.size)

[[1.  2.1 3.3]
 [4.  5.  6.5]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [14]:
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
print(a3)
print(type(a3))
print(a3.dtype)
print(a3.shape)
print(a3.ndim)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
int64
(2, 3, 3)
3
18
